In [2]:
import numpy as np

In [3]:
np.__version__

'1.18.5'

In [12]:
# A maneira mais facil de criar um numpy array é primeiramente criar uma lista e depois converter para um array:

lista = [9,0,8,6,1]

arr = np.array(lista)

In [13]:
arr

array([9, 0, 8, 6, 1])

Funções "matemáticas": min, max, sum,sqrt, round

min: Menor valor do array;

max: Maior valor do array;

sum: Soma dos valores do array;

sqrt: Raiz quadrada do array;

round: Arredonda os valores do array;

In [14]:
print("Array:", arr)

print("Valor Minimo:", np.min(arr))
print("Valor Máximo:", np.max(arr))
print("Soma:", np.sum(arr))
print("Raiz Quadrada:", np.sqrt(arr))
print("Arredondamento:", np.round(np.sqrt(arr)))

Array: [9 0 8 6 1]
Valor Minimo: 0
Valor Máximo: 9
Soma: 24
Raiz Quadrada: [3.         0.         2.82842712 2.44948974 1.        ]
Arredondamento: [3. 0. 3. 2. 1.]


Funções Estatistica: mean, std, percentile

mean: Média aritmética dos valores do array;

std: Desvio padrão dos valores do array;

percentile: Retorna o valor do percentil especificado de acordo com os valores do array

In [15]:
#Média

print("Array:", arr)
print('Média:', np.mean(arr))

Array: [9 0 8 6 1]
Média: 4.8


In [16]:
#STD

print("Desvio Padrão:", np.std(arr))

Desvio Padrão: 3.655133376499413


In [17]:
#Percentil 50 == Mediana é o valor que separa a metade maior e a metade menor de uma amostra ordenada

print('Percentil 50:', np.percentile(arr,50))

Percentil 50: 6.0


Concatenando Arrays

In [18]:
#Funções utilizadas para "colar" dois arrays

ar1 = np.arange(10,20,2)
ar2 = np.arange(20,30,2)

print(ar1)
print(ar2)

[10 12 14 16 18]
[20 22 24 26 28]


In [20]:
# c_ é uma função para concatenar dois arrays == muito utilizado na área de DS para criação de base de dados,
# pois geralmente pegamos variáveis de diversas tabelas e nesse caso, podemos concatenar nada para trasnformar
# em uma única tabela:

#mantém a ordem dos dados:

arr_c_ = np.c_[ar1, ar2]

print(arr_c_)

print(arr_c_.shape)

[[10 20]
 [12 22]
 [14 24]
 [16 26]
 [18 28]]
(5, 2)


In [21]:
# Concatena dois arrays, unidimensionais na horizontal:

arr_concatenate = np.concatenate([ar1, ar2])
print(arr_concatenate)

print(arr_concatenate.shape)

[10 12 14 16 18 20 22 24 26 28]
(10,)


In [26]:
arr1_bdim = np.array([[1,2], [6,4]])
arr2_bdim = np.array([[0,8], [3,3]])

print(arr1_bdim)
print('---------')
print(arr2_bdim)

# A função v-stack ela opera um vertical stack, ou seja, ela "cola" os arrays na vertical:

arr_v_stack = np.vstack((arr1_bdim, arr2_bdim))
print('-----------')
print(arr_v_stack)

[[1 2]
 [6 4]]
---------
[[0 8]
 [3 3]]
-----------
[[1 2]
 [6 4]
 [0 8]
 [3 3]]


In [28]:
# A função h-stack ela opera um horizontal stack, ela "cola" os arrays na horizontal:
arr_h_stack = np.hstack((arr1_bdim, arr2_bdim))

print(arr_h_stack)

[[1 2 0 8]
 [6 4 3 3]]


Função dot

Array unidimensional: A função dot faz o produto interno

Array bidimensional: A função dot faz multiplicação das matrizes

In [29]:
#Quando temos arrays unidimensionais, a função dot performa o produto interno

print(ar1)
print(ar2)

np.dot(ar1,ar2)

[10 12 14 16 18]
[20 22 24 26 28]


1720

In [30]:
#Quando temos arrays unidimensionais a função dot performa multiplicação de matrizes

print(arr1_bdim)
print('*********')
print(arr2_bdim)

np.dot(arr1_bdim,arr2_bdim)

[[1 2]
 [6 4]]
*********
[[0 8]
 [3 3]]


array([[ 6, 14],
       [12, 60]])

In [31]:
#Existe uma diferença de utilizarmos a multiplicação usual:

print(arr1_bdim)
print('*********')
print(arr2_bdim)

arr1_bdim*arr2_bdim

[[1 2]
 [6 4]]
*********
[[0 8]
 [3 3]]


array([[ 0, 16],
       [18, 12]])

Função T

In [32]:
#Calcula a transposta da matriz:
arr3_dbim = np.arange(10,30,2)

print(arr3_dbim)

[10 12 14 16 18 20 22 24 26 28]


In [33]:
arr3_dbim = arr3_dbim.reshape(2,5)

print(arr3_dbim)

[[10 12 14 16 18]
 [20 22 24 26 28]]


In [34]:
#Transposta de uma matriz: nova matriz onde as linhas da matriz anterior viram colunas:

arr3_dbim.T

array([[10, 20],
       [12, 22],
       [14, 24],
       [16, 26],
       [18, 28]])